import 'dart:async';
import 'dart:convert' show base64;
import 'dart:ui';

import 'package:collection/collection.dart';
import 'package:flame/src/flame.dart';
import 'package:flutter/cupertino.dart' show debugPrintStack;
import 'package:flutter/painting.dart';
import 'package:flutter/services.dart';
import 'package:plato/plato.dart';

const _logr = Debugr(true, prefix: 'flame.images');

class Images {
  Images({
    String prefix = 'assets/images/',
    AssetBundle? bundle,
  }) : _prefix = prefix,
       bundle = bundle ?? Flame.bundle;

  /// The the byte length of cached items
  int get length => _assets.values.map((a) => a.length).sum;

  @override
  String toString() => Printr.print(this,
    'items=${_assets.length}',
    _assets.values.map((a) => a.name).join(', '),
    'length=$length',
  );

  final _assets = LruCache<String, _ImageAsset>();

  /// The [AssetBundle] from which images are loaded.
  /// defaults to [Flame.bundle].
  AssetBundle bundle;

  /// Path prefix to the project's directory with images.
  ///
  /// This path is relative to the project's root, and the default prefix is
  /// "assets/images/". If necessary, you may change this prefix at any time.
  /// A prefix must be a valid directory name and end with "/" (empty prefix is
  /// also allowed).
  ///
  /// The prefix is **not** part of the keys of the images stored in this cache.
  /// For example, if you load image `player.png`, then it will be searched at
  /// location `prefix + "player.png"` but stored in the cache under the key
  /// `"player.png"`.
  String get prefix => _prefix;
  late String _prefix;
  set prefix(String value) {
    assert(
      value.isEmpty || value.endsWith('/'),
      'Prefix must be empty or end with a "/"',
    );
    _prefix = value;
  }

  /// Adds the [image] into the cache under the key [name].
  ///
  /// The cache will assume the ownership of the [image], and will properly
  /// dispose of it at the end.
  void add(String name, Image image) {
    _assets.get(name)?.dispose();
    _assets.put(name, _ImageAsset.fromImage(name, image));
  }

  /// Transform the base64 encoded image into an [Image] and adds it into the
  /// cache.
  Future<void> addFromBase64Data(String name, String base64Data) async {
    _assets.get(name)?.dispose();
    final image = await _fetchFromBase64(base64Data);
    _assets.put(name, _ImageAsset.fromImage(name, image));
  }

  /// If the image with [name] exists in the cache that is returned, otherwise
  /// the image generated by [imageGenerator] is returned.
  ///
  /// If the [imageGenerator] is used, the resulting [Image] is stored with
  /// [name] in the cache.
  Future<Image> fetchOrGenerate(
    String name,
    Future<Image> Function() imageGenerator,
  ) => _assets.putIfAbsent(name, (_) => _ImageAsset.future(
      name,
      imageGenerator(),
    )).retrieveAsync();

  /// Removes the image [name] from the cache.
  ///
  /// No error is raised if the image [name] is not present in the cache.
  ///
  /// This calls [Image.dispose], so make sure that you don't use the previously
  /// cached image once it is cleared (removed) from the cache.
  void clear(String name) {
    final removedAsset = _assets.remove(name);
    removedAsset?.dispose();
  }

  /// Removes all cached images.
  ///
  /// This calls [Image.dispose] for all images in the cache, so make sure that
  /// you don't use any of the previously cached images once [clearCache] has
  /// been called.
  void clearCache() {
    _assets.values.forEach((a) => a.dispose());
    _assets.clear();
  }

  /// Returns the image [name] from the cache.
  ///
  /// The image returned can be used as long as it remains in the cache, but
  /// doesn't need to be explicitly disposed.
  ///
  /// If you want to retain the image even after you remove it from the cache,
  /// then you can call `Image.clone()` on it.
  Image fromCache(String name) {
    final asset = _assets.get(name);
    assert(
      asset != null,
      'Tried to access an image "$name" that does not exist in the cache. Make '
      'sure to load() an image before accessing it',
    );
    assert(
      asset!.image != null,
      'Tried to access an image "$name" before it was loaded. Make sure to '
      'await the future from load() before using this method',
    );
    return asset!.image!;
  }

  /// Loads the specified image with [fileName] into the cache.
  /// By default the key in the cache is the [fileName], if another key is
  /// desired, specify the optional [key] argument.
  Future<Image> load(String fileName, {String? key}) =>
    _assets.putIfAbsent(key ?? fileName, (_) => _ImageAsset.future(
      fileName,
      _fetchToMemory(fileName),
    )).retrieveAsync();

  /// Loads all images with the specified [fileNames] into the cache.
  Future<List<Image>> loadAll(List<String> fileNames) {
    return Future.wait(fileNames.map(load));
  }

  /// Loads all images from the specified (or default) [prefix] into the cache.
  Future<List<Image>> loadAllImages() {
    throw StateError('do not call loadAllImages()');
    // return loadAllFromPattern(
    //   RegExp(
    //     r'\.(png|jpg|jpeg|svg|gif|webp|bmp|wbmp)$',
    //     caseSensitive: false,
    //   ),
    // );
  }

  /// Loads all images in the [prefix]ed path that are matching the specified
  /// pattern.
  Future<List<Image>> loadAllFromPattern(Pattern pattern) async {
    throw StateError('do not call loadAllFromPattern()');
    // final manifest = await AssetManifest.loadFromAssetBundle(bundle);
    // final imagePaths = manifest
    //     .listAssets()
    //     .where((path) {
    //       return path.startsWith(_prefix) &&
    //           path.toLowerCase().contains(pattern);
    //     })
    //     .map((path) => path.replaceFirst(_prefix, ''));
    // return loadAll(imagePaths.toList());
  }

  /// Whether the cache contains the specified [key] or not.
  bool containsKey(String key) => _assets.containsKey(key);

  /// Returns the list of keys in the cache.
  List<String> get keys => _assets.keys.toList();

  String? findKeyForImage(Image image) =>
    _assets.keys.firstWhere(
      (k) => _assets.get(k)?.image?.isCloneOf(image) ?? false,
    );

  /// Waits until all currently pending image loading operations complete.
  Future<void> ready() {
    return Future.wait(_assets.values.map((asset) => asset.retrieveAsync()));
  }

  Future<Image> fromBase64(String key, String base64) =>
    _assets.putIfAbsent(key, (_) => _ImageAsset.future(
      key,
      _fetchFromBase64(base64),
    )).retrieveAsync();

  Future<Image> _fetchFromBase64(String base64Data) {
    final data = base64Data.substring(base64Data.indexOf(',') + 1);
    final bytes = base64.decode(data);
    _logr.log(() => '_fetchFromBase64 > ${base64Data.length}');
    return decodeImageFromList(bytes);
  }

  Future<Image> _fetchToMemory(String name) async {
    final bytes = await Plato().provider.assetLoader.loadBytes('$_prefix$name');
    // final watch = Stopwatch()..start();
    // final data = await bundle.load('$_prefix$name');
    // _logr.log(() => '_fetchToMemory LOAD > $name > ${watch.elapsedMilliseconds}');
    // watch.reset();
    // final bytes = Uint8List.view(data.buffer);
    // _logr.log(() => '_fetchToMemory BYTES > $name > ${watch.elapsedMilliseconds}');
    _logr.log(() => '_fetchToMemory > $name ${bytes.length}');
    // if (name.contains('stadium')) {
    //   debugPrintStack(maxFrames: 20);
    // }
    return decodeImageFromList(bytes);
  }
}

/// Individual entry in the [Images] cache.
///
/// This class owns the [Image] object, which can be disposed of using the
/// [dispose] method.
class _ImageAsset {

  final String name;

  _ImageAsset.future(this.name, Future<Image> future) : _future = future {
    _future!.then((image) {
      _image = image;
      _future = null;
    });
  }

  int get length {
    final i = _image;
    if (i == null) {
      return 0;
    } else {
      return i.width * i.height * 4;
    }
  }

  _ImageAsset.fromImage(this.name, Image image) : _image = image;

  Image? get image => _image;
  Image? _image;

  Future<Image>? _future;

  Future<Image> retrieveAsync() => _future ?? Future.value(_image);

  /// Properly dispose of an image asset.
  void dispose() {
    if (_image != null) {
      _image!.dispose();
      _image = null;
    }
    if (_future != null) {
      _future!.then((image) => image.dispose());
      _future = null;
    }
  }
}
